# pnpm-workspace.yaml
packages:
  - 'packages/shared'
  - 'packages/core'
  - 'packages/backend'
  - 'packages/script'
  - 'packages/service'
  - 'packages/app'
  - 'packages/nightwatch-devtools'
  - 'packages/selenium-devtools'
  - 'packages/elements'
  - 'examples/wdio'
  - 'examples/selenium'
  - 'examples/nightwatch'
