# GENERATED by scripts/gen_contract.py from packages/shared.
# Do not edit by hand — run the script to regenerate.
CONTRACT_VERSION = "1.0.0"

SCOPE_METADATA = "metadata"
SCOPE_COMMANDS = "commands"
SCOPE_CONSOLE_LOGS = "consoleLogs"
SCOPE_NETWORK_REQUESTS = "networkRequests"
SCOPE_SUITES = "suites"

DATA_SCOPES = frozenset(['actionSnapshots', 'commands', 'config', 'consoleLogs', 'logs', 'metadata', 'mutations', 'networkRequests', 'screencast', 'sources', 'suites'])
CONTROL_SCOPES = frozenset(['clearCommands', 'clearExecutionData', 'clientConnected', 'clientDisconnected', 'config', 'replaceCommand', 'testStopped'])
