# GENERATED by scripts/gen_contract.py from packages/shared.
# Do not edit by hand — run the script to regenerate.
CONTRACT_VERSION = "1.0.0"

SCOPE_METADATA = "metadata"
SCOPE_COMMANDS = "commands"
SCOPE_CONSOLE_LOGS = "consoleLogs"
SCOPE_NETWORK_REQUESTS = "networkRequests"
SCOPE_SUITES = "suites"
SCOPE_SCREENCAST = "screencast"
SCOPE_SOURCES = "sources"
SCOPE_MUTATIONS = "mutations"

DATA_SCOPES = frozenset(['actionSnapshots', 'commands', 'config', 'consoleLogs', 'logs', 'metadata', 'mutations', 'networkRequests', 'screencast', 'screencastFrames', 'sources', 'suites'])
CONTROL_SCOPES = frozenset(['clearCommands', 'clearExecutionData', 'clientConnected', 'clientDisconnected', 'config', 'replaceCommand', 'testStopped'])

COLLECTOR_PATH = "/api/collector"
COLLECTOR_SINK_GLOBAL = "__wdioTraceSink"
COLLECTOR_MUTATION_CHANNEL = "wdio-trace-mutations"
RUNNER_ID = "selenium-webdriver"
TEST_RUNNER_IDS = frozenset(['cucumber', 'jasmine', 'mocha', 'nightwatch', 'nightwatch-cucumber', 'selenium-webdriver'])

WORKER_QUERY_RUN_ID = "runId"
ENV_RUN_ID = "DEVTOOLS_RUN_ID"

RERUN_SLOT_TEST_ID = "{{testId}}"
ENV_RUNNER_CWD = "DEVTOOLS_RUNNER_CWD"

ENV_REUSE = "DEVTOOLS_APP_REUSE"
ENV_REUSE_HOST = "DEVTOOLS_APP_HOST"
ENV_REUSE_PORT = "DEVTOOLS_APP_PORT"
