# GENERATED by scripts/gen_contract.py from packages/shared/wire-schema.json.
# Do not edit by hand — run the script to regenerate.
from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional, TypedDict, Union

__all__ = ['AccessibilityNode', 'ActionSnapshot', 'BaselineClearedWsPayload', 'BaselineSavedWsPayload', 'ClearExecutionDataWsPayload', 'CommandLog', 'CommandLogPoint', 'ConsoleLog', 'DeviceInfo', 'DocumentInfo', 'DocumentInfoDocumentInfo', 'DocumentInfoHeaders', 'ElementScriptsResponse', 'Metadata', 'NetworkRequest', 'NetworkRequestResponse', 'PerformanceData', 'PerformanceDataNavigation', 'PerformanceDataNavigationTiming', 'PerformanceDataResources', 'PreservedAttempt', 'PreservedAttemptTest', 'PreservedAttemptWindow', 'PreservedStep', 'ReplaceCommandWsPayload', 'ScreencastFrame', 'ScreencastInfo', 'SerializedError', 'SuiteStats', 'TestError', 'TestErrorMatcherResult', 'TestStats', 'TraceExportRequest', 'TraceExportResult', 'TraceMutation', 'Viewport']


class _AccessibilityNodeRequired(TypedDict):
    role: str
    name: str
    selector: str
    depth: float
    level: Union[str, float]
    disabled: str
    checked: str
    expanded: str
    selected: str
    pressed: str
    required: str
    readonly: str


class AccessibilityNode(_AccessibilityNodeRequired, total=False):
    isInViewport: bool


class _ActionSnapshotRequired(TypedDict):
    timestamp: float
    command: str


class ActionSnapshot(_ActionSnapshotRequired, total=False):
    url: str
    title: str
    screenshot: str
    elements: List[Any]
    snapshotText: str
    accessibilityTree: List[AccessibilityNode]


class BaselineClearedWsPayload(TypedDict):
    testUid: str


class BaselineSavedWsPayload(TypedDict):
    testUid: str
    attempt: PreservedAttempt


class ClearExecutionDataWsPayload(TypedDict, total=False):
    uid: str
    entryType: Literal['test', 'suite']
    clearSuiteTree: bool
    runStart: bool


class _CommandLogRequired(TypedDict):
    command: str
    args: List[Any]
    timestamp: float


class CommandLog(_CommandLogRequired, total=False):
    title: str
    result: Any
    error: SerializedError
    startTime: float
    sequence: float
    callSource: str
    screenshot: str
    testUid: str
    performance: PerformanceData
    cookies: str
    documentInfo: DocumentInfo
    id: float
    stepUid: str
    snapshotText: str
    point: CommandLogPoint
    selector: str


class CommandLogPoint(TypedDict):
    x: float
    y: float


class _ConsoleLogRequired(TypedDict):
    type: Literal['trace', 'debug', 'log', 'info', 'warn', 'error']
    args: List[Any]
    timestamp: float


class ConsoleLog(_ConsoleLogRequired, total=False):
    source: Literal['browser', 'test', 'terminal']


class _DeviceInfoRequired(TypedDict):
    platform: Literal['android', 'ios']


class DeviceInfo(_DeviceInfoRequired, total=False):
    name: str
    version: str


class DocumentInfo(TypedDict):
    url: str
    title: str
    headers: DocumentInfoHeaders
    documentInfo: DocumentInfoDocumentInfo


class DocumentInfoDocumentInfo(TypedDict):
    readyState: str
    referrer: str
    characterSet: str


class DocumentInfoHeaders(TypedDict):
    userAgent: str
    language: str
    platform: str


class ElementScriptsResponse(TypedDict):
    accessibilityTree: str
    elements: str


class _MetadataRequired(TypedDict):
    type: Literal['standalone', 'testrunner']


class Metadata(_MetadataRequired, total=False):
    url: str
    options: Any
    capabilities: Any
    viewport: Viewport
    sessionId: str
    testEnv: str
    host: str
    modulePath: str
    desiredCapabilities: Dict[str, Any]
    runner: Literal['mocha', 'jasmine', 'cucumber', 'nightwatch', 'nightwatch-cucumber', 'selenium-webdriver']
    device: DeviceInfo


class _NetworkRequestRequired(TypedDict):
    id: str
    url: str
    method: str
    timestamp: float
    startTime: float
    type: Literal['document', 'stylesheet', 'script', 'image', 'font', 'fetch', 'xhr', 'other']


class NetworkRequest(_NetworkRequestRequired, total=False):
    headers: Dict[str, str]
    cookies: List[Any]
    status: float
    statusText: str
    endTime: float
    time: float
    initiator: str
    requestHeaders: Dict[str, str]
    responseHeaders: Dict[str, str]
    navigation: str
    redirectChain: List[Any]
    children: List[NetworkRequest]
    response: NetworkRequestResponse
    error: str
    requestBody: str
    responseBody: str
    size: float


class NetworkRequestResponse(TypedDict):
    fromCache: bool
    headers: Dict[str, str]
    mimeType: str
    status: float


class PerformanceData(TypedDict, total=False):
    navigation: PerformanceDataNavigation
    resources: List[PerformanceDataResources]


class PerformanceDataNavigation(TypedDict):
    url: str
    timing: PerformanceDataNavigationTiming


class PerformanceDataNavigationTiming(TypedDict, total=False):
    loadTime: float
    domReady: float
    responseTime: float
    dnsLookup: float
    tcpConnection: float
    serverResponse: float


class PerformanceDataResources(TypedDict):
    url: str
    duration: float
    size: float
    type: str
    startTime: float
    responseEnd: float


class _PreservedAttemptRequired(TypedDict):
    testUid: str
    scope: Literal['test', 'suite']
    capturedAt: float
    window: PreservedAttemptWindow
    test: PreservedAttemptTest
    commands: List[CommandLog]
    consoleLogs: List[ConsoleLog]
    networkRequests: List[NetworkRequest]
    mutations: List[Any]
    sources: Dict[str, str]


class PreservedAttempt(_PreservedAttemptRequired, total=False):
    steps: List[PreservedStep]


class PreservedAttemptTest(TypedDict, total=False):
    title: str
    fullTitle: str
    file: str
    callSource: str
    start: float
    end: float
    duration: float
    state: Literal['passed', 'failed', 'skipped', 'pending', 'running']
    error: TestError


class PreservedAttemptWindow(TypedDict):
    start: float
    end: float


class _PreservedStepRequired(TypedDict):
    uid: str


class PreservedStep(_PreservedStepRequired, total=False):
    title: str
    fullTitle: str
    start: float
    end: float
    state: Literal['passed', 'failed', 'skipped', 'pending', 'running']
    error: TestError


class ReplaceCommandWsPayload(TypedDict):
    oldTimestamp: float
    command: CommandLog


class ScreencastFrame(TypedDict):
    data: str
    timestamp: float


class ScreencastInfo(TypedDict, total=False):
    sessionId: str
    videoPath: str
    videoFile: str
    frameCount: float
    duration: float
    startTime: float


class _SerializedErrorRequired(TypedDict):
    name: str
    message: str


class SerializedError(_SerializedErrorRequired, total=False):
    stack: str


class _SuiteStatsRequired(TypedDict):
    uid: str
    cid: str
    title: str
    fullTitle: str
    type: Literal['suite']
    file: str
    start: str
    tests: List[Union[str, TestStats]]
    suites: List[SuiteStats]
    hooks: List[Any]
    _duration: float


class SuiteStats(_SuiteStatsRequired, total=False):
    state: Literal['passed', 'failed', 'skipped', 'pending', 'running']
    end: Optional[str]
    parent: str
    callSource: str
    order: float
    featureFile: str


class TestError(TypedDict, total=False):
    message: str
    name: str
    stack: str
    expected: Any
    actual: Any
    matcherResult: TestErrorMatcherResult


class TestErrorMatcherResult(TypedDict, total=False):
    expected: Any
    actual: Any
    message: str


class _TestStatsRequired(TypedDict):
    uid: str
    cid: str
    title: str
    fullTitle: str
    parent: str
    state: Literal['passed', 'failed', 'skipped', 'pending', 'running']
    start: str
    end: Optional[str]
    type: Literal['test']
    file: str
    retries: float
    _duration: float


class TestStats(_TestStatsRequired, total=False):
    error: SerializedError
    hooks: List[Any]
    callSource: str
    order: float


class _TraceExportRequestRequired(TypedDict):
    requestId: str
    outputDir: str
    sessionId: str


class TraceExportRequest(_TraceExportRequestRequired, total=False):
    format: Literal['zip', 'ndjson-directory']
    fileStem: str
    tracePolicy: Literal['on', 'retain-on-failure', 'retain-on-first-failure', 'on-first-retry', 'on-all-retries', 'retain-on-failure-and-retries']
    traceGranularity: Literal['test', 'session']


class _TraceExportResultRequired(TypedDict):
    requestId: str


class TraceExportResult(_TraceExportResultRequired, total=False):
    path: str
    paths: List[str]
    error: str
    declinedByPolicy: bool


class _TraceMutationRequired(TypedDict):
    type: Literal['attributes', 'characterData', 'childList']
    addedNodes: List[Any]
    removedNodes: List[str]
    timestamp: float


class TraceMutation(_TraceMutationRequired, total=False):
    attributeName: str
    attributeNamespace: str
    attributeValue: str
    newTextContent: str
    oldValue: str
    target: str
    previousSibling: str
    nextSibling: str
    url: str


class Viewport(TypedDict):
    width: float
    height: float
    offsetLeft: float
    offsetTop: float
    scale: float
