"""The page-side element scripts, fetched from the backend.

These are what fills the trace's A11y tab: one script reads the accessibility
tree, the other the interactable elements and their rects. Both are browser
source, and both live in `@wdio/devtools-shared` — TypeScript this adapter
cannot import. So the backend serves them, exactly as it already serves the
page collector, and for the same reason: a copy per language is a copy that
drifts, and #284/#285/#286 are three fixes that reached the JS adapters and
never reached this one.

The runner matters. The scripts bake in a locator dialect — a WDIO run wants
`a*=Logout`, a protocol-level one wants XPath — so the request names the runner
and the backend generates accordingly. Getting that wrong yields locators that
look right and select nothing.

Fetched once per run and cached, because they are re-run after every command;
a failure is cached too, so a backend without the route (an older one) costs one
request rather than one per action. Nothing here may raise into the user's test:
a missing A11y tab is worth less than a broken run.
"""

from __future__ import annotations

import json
import logging
import urllib.error
import urllib.parse
import urllib.request
from typing import Optional

from ._contract import ELEMENT_SCRIPTS_PATH, RUNNER_ID
from .constants import ELEMENT_SCRIPTS_FETCH_TIMEOUT_S, LOGGER_NAME
from .types import ElementScripts

_log = logging.getLogger(f"{LOGGER_NAME}.elements")

#: Keyed by the backend it came from: a rerun attaches to a different one, and
#: serving a script generated by another version would be worse than none.
_cache: dict = {"origin": None, "scripts": None, "settled": False}


def reset_cache() -> None:
    """Drop the cached scripts. Called on teardown so a re-enable re-fetches."""
    _cache.update(origin=None, scripts=None, settled=False)


def scripts_url(host: str, port: int) -> str:
    """The endpoint on a backend, with the runner this adapter reports as.

    A bare IPv6 literal has to be bracketed or urllib reads the last colon as
    the port separator — the same handling `collector_url` needs.
    """
    url_host = f"[{host}]" if ":" in host and not host.startswith("[") else host
    query = urllib.parse.urlencode({"runner": RUNNER_ID})
    return f"http://{url_host}:{port}{ELEMENT_SCRIPTS_PATH}?{query}"


def fetch(host: str, port: int) -> Optional[ElementScripts]:
    """``{"accessibilityTree": str, "elements": str}`` from the backend, or None.

    None on anything at all — no route (a backend older than this feature), a
    refused connection, a body that is not the shape promised. The caller then
    captures no element tree, which costs the A11y tab and nothing else.
    """
    origin = (host, port)
    if _cache["settled"] and _cache["origin"] == origin:
        return _cache["scripts"]

    scripts: Optional[ElementScripts] = None
    try:
        with urllib.request.urlopen(  # noqa: S310 — a loopback backend we launched
            scripts_url(host, port), timeout=ELEMENT_SCRIPTS_FETCH_TIMEOUT_S
        ) as response:
            body = json.loads(response.read().decode("utf-8"))
        if isinstance(body, dict) and all(
            isinstance(body.get(k), str) and body.get(k)
            for k in ("accessibilityTree", "elements")
        ):
            scripts = {
                "accessibilityTree": body["accessibilityTree"],
                "elements": body["elements"],
            }
        else:
            _log.debug("element scripts: unexpected response shape")
    except (urllib.error.URLError, OSError, ValueError) as exc:
        _log.debug("element scripts unavailable (%s); no A11y tree this run", exc)

    _cache.update(origin=origin, scripts=scripts, settled=True)
    return scripts
