import * as fs from 'node:fs'
import * as net from 'node:net'
import * as path from 'node:path'
import { parse as parseStackTrace } from 'stacktrace-parser'
import logger from '@wdio/logger'
import {
  ANSI_REGEX,
  LOG_LEVEL_PATTERNS,
  TEST_PATH_PATTERN,
  TEST_FILE_PATTERN,
  CONFIG_FILENAMES
} from '../constants.js'
import type {
  ConsoleLog,
  LogLevel,
  NightwatchTestCase,
  TestFileMetadata,
  StepLocation
} from '../types.js'

export function determineTestState(
  testcase: NightwatchTestCase
): 'passed' | 'failed' | 'skipped' {
  if (testcase.passed === 0 && testcase.failed === 0) {
    return 'skipped'
  }
  return testcase.passed > 0 && testcase.failed === 0 ? 'passed' : 'failed'
}

// Track test occurrences to generate stable UIDs
const signatureCounters = new Map<string, number>()

/**
 * Generate stable UID for test/suite.
 * Accepts either (item: SuiteStats | TestStats) or (file: string, name: string).
 */
export function generateStableUid(itemOrFile: any, name?: string): string {
  let file: string, testName: string
  if (
    typeof itemOrFile === 'object' &&
    itemOrFile !== null &&
    name === undefined
  ) {
    file = itemOrFile.file || ''
    testName = String(itemOrFile.fullTitle || itemOrFile.title)
  } else {
    file = itemOrFile || ''
    testName = String(name || '')
  }
  const signature = `${file}::${testName}`
  const count = signatureCounters.get(signature) || 0
  signatureCounters.set(signature, count + 1)
  const hashInput = count > 0 ? `${signature}::${count}` : signature
  const hash = hashInput
    .split('')
    .reduce((acc, char) => ((acc << 5) - acc + char.charCodeAt(0)) | 0, 0)
  return `stable-${Math.abs(hash).toString(36)}`
}

/** Reset counters at the start of each test run. */
export function resetSignatureCounters() {
  signatureCounters.clear()
}

/**
 * Compute a purely deterministic UID from arbitrary string parts.
 * Unlike generateStableUid this NEVER uses the signature counter, so calling
 * it multiple times with the same inputs always returns the same value.
 * Use this wherever the same entity (e.g. a Cucumber scenario) must map to
 * the same UID across retries.
 */
export function deterministicUid(...parts: string[]): string {
  const hash = parts
    .join('::')
    .split('')
    .reduce((acc, char) => ((acc << 5) - acc + char.charCodeAt(0)) | 0, 0)
  return `stable-${Math.abs(hash).toString(36)}`
}

/** Returns true if a stack frame belongs to user code (not dependencies, internals, or build output). */
function isUserCodeFrame(frame: {
  file?: string | null
}): frame is { file: string } {
  const { file } = frame
  return !!(
    file &&
    !file.includes('/node_modules/') &&
    !file.includes('<anonymous>') &&
    !file.includes('node:internal') &&
    !file.includes('/dist/') &&
    !file.includes('/index.js')
  )
}

/** Strips the file:// protocol and any trailing :line:col suffix from a file path. */
function normalizeFilePath(filePath: string): string {
  return filePath.replace(/^file:\/\//, '').split(':')[0]
}

/**
 * Find test file from stack trace.
 * Parses call stack to find the first frame that looks like a test file.
 */
export function findTestFileFromStack(): string | undefined {
  const stack = new Error().stack
  if (!stack) {
    return undefined
  }

  const frame = parseStackTrace(stack).find(
    (f) =>
      isUserCodeFrame(f) &&
      (TEST_PATH_PATTERN.test(f.file) || TEST_FILE_PATTERN.test(f.file))
  )
  if (!frame?.file) {
    return undefined
  }

  const filePath = normalizeFilePath(frame.file)
  return fs.existsSync(filePath) ? filePath : undefined
}

/**
 * Extract suite and test names — and their line numbers — from a test file.
 * Returns a TestFileMetadata object used to build `callSource` strings for
 * the TestLens eye-icon navigation.
 */
export function extractTestMetadata(filePath: string): TestFileMetadata {
  const result: TestFileMetadata = {
    suiteTitle: null,
    suiteLine: null,
    testNames: [],
    testLines: []
  }
  if (!fs.existsSync(filePath)) {
    return result
  }

  try {
    const lines = fs.readFileSync(filePath, 'utf-8').split('\n')
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i]
      const lineNum = i + 1
      if (result.suiteTitle === null) {
        const m = line.match(
          /(?:describe|suite|context)\s*\(\s*['"`]([^'"`]+)['"`]/
        )
        if (m) {
          result.suiteTitle = m[1]
          result.suiteLine = lineNum
        }
      }
      // describe/it style: it('name', ...) / test('name', ...) / specify('name', ...)
      const itMatch = line.match(
        /(?:it|test|specify)\s*\(\s*['"`]([^'"`]+)['"`]/
      )
      if (itMatch) {
        result.testNames.push(itMatch[1])
        result.testLines.push(lineNum)
        continue
      }
      // Object-export style (NightwatchTests): 'Test name': () => { / 'Test name': function() {
      // This is the default format generated by `npx nightwatch --yes`
      const objMatch = line.match(
        /^\s*['"`]([^'"`]+)['"`]\s*:\s*(?:async\s+)?(?:\([^)]*\)\s*=>|function\s*\()/
      )
      if (objMatch) {
        result.testNames.push(objMatch[1])
        result.testLines.push(lineNum)
      }
    }
  } catch {
    // skip unparseable files
  }
  return result
}

/**
 * Get call source info from stack trace.
 * Returns { filePath, callSource } where callSource has the filename:line format.
 */
export function getCallSourceFromStack(): {
  filePath: string | undefined
  callSource: string
} {
  const stack = new Error().stack
  if (!stack) {
    return { filePath: undefined, callSource: 'unknown:0' }
  }

  const frame = parseStackTrace(stack).find(isUserCodeFrame)
  if (!frame?.file) {
    return { filePath: undefined, callSource: 'unknown:0' }
  }

  const filePath = normalizeFilePath(frame.file)
  return { filePath, callSource: `${filePath}:${frame.lineNumber ?? 0}` }
}

/**
 * Find test file by searching the workspace for a matching filename.
 * Used when the stack trace doesn't have the file yet (e.g. in beforeEach).
 */
export function findTestFileByName(
  filename: string,
  workspaceRoot?: string
): string | undefined {
  if (!filename || !workspaceRoot) {
    return undefined
  }

  const baseFilename = filename.replace(/\.[cm]?[jt]sx?$/, '')

  function searchDir(dir: string, depth = 0): string | undefined {
    if (depth > 5) {
      return undefined
    }
    try {
      for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
        const fullPath = path.join(dir, entry.name)
        if (entry.isDirectory()) {
          const found = searchDir(fullPath, depth + 1)
          if (found) {
            return found
          }
        } else if (
          TEST_FILE_PATTERN.test(entry.name) &&
          entry.name.replace(TEST_FILE_PATTERN, '') === baseFilename
        ) {
          return fullPath
        }
      }
    } catch {
      // Permission denied or other error — skip
    }
    return undefined
  }

  return searchDir(workspaceRoot)
}

// ---------------------------------------------------------------------------
// Console / log helpers (used by SessionCapturer)
// ---------------------------------------------------------------------------

/**
 * Strip ANSI escape codes from a string.
 */
export const stripAnsiCodes = (text: string): string =>
  text.replace(ANSI_REGEX, '')

/** Infer a log level from the text content of a line. */
export function detectLogLevel(text: string): LogLevel {
  const normalised = stripAnsiCodes(text).toLowerCase()
  for (const { level, pattern } of LOG_LEVEL_PATTERNS) {
    if (pattern.test(normalised)) {
      return level
    }
  }
  return 'log'
}

/**
 * Build a ConsoleLog entry.
 */
export function createConsoleLogEntry(
  type: LogLevel,
  args: any[],
  source: string
): ConsoleLog {
  return { timestamp: Date.now(), type, args, source }
}

/** Map a Chrome DevTools log level string to our LogLevel union. */
export function chromeLogLevelToLogLevel(
  level: string | { value?: number; name?: string }
): LogLevel {
  const levelName = (
    typeof level === 'object' ? (level?.name ?? '') : (level ?? '')
  ).toUpperCase()
  switch (levelName) {
    case 'SEVERE':
      return 'error'
    case 'WARNING':
      return 'warn'
    case 'INFO':
      return 'info'
    case 'DEBUG':
      return 'debug'
    default:
      return 'log'
  }
}

/** Derive a human-readable request type from URL and MIME type. */
export function getRequestType(url: string, mimeType?: string): string {
  const contentType = mimeType?.toLowerCase() ?? ''
  const urlLower = url.toLowerCase()

  if (contentType.includes('text/html')) {
    return 'document'
  }
  if (contentType.includes('text/css')) {
    return 'stylesheet'
  }
  if (
    contentType.includes('javascript') ||
    contentType.includes('ecmascript')
  ) {
    return 'script'
  }
  if (contentType.includes('image/')) {
    return 'image'
  }
  if (contentType.includes('font/') || contentType.includes('woff')) {
    return 'font'
  }
  if (contentType.includes('application/json')) {
    return 'fetch'
  }

  if (urlLower.endsWith('.html') || urlLower.endsWith('.htm')) {
    return 'document'
  }
  if (urlLower.endsWith('.css')) {
    return 'stylesheet'
  }
  if (urlLower.endsWith('.js') || urlLower.endsWith('.mjs')) {
    return 'script'
  }
  if (/\.(png|jpg|jpeg|gif|svg|webp|ico)$/.test(urlLower)) {
    return 'image'
  }
  if (/\.(woff|woff2|ttf|eot|otf)$/.test(urlLower)) {
    return 'font'
  }

  return 'xhr'
}

// ---------------------------------------------------------------------------
// Cucumber helpers
// ---------------------------------------------------------------------------

/**
 * Parse a feature file for a given scenario in a single pass, returning:
 *  - `featureLine`  — 1-based line of the `Feature:` declaration
 *  - `scenarioLine` — 1-based line of the matching `Scenario:` block
 *  - `stepLines`    — 1-based line numbers for each step (for TestLens navigation)
 *  - `stepKeywords` — BDD keyword (Given/When/Then/And/But) for each step (for labels)
 */
export function parseCucumberScenario(
  featureContent: string,
  scenarioName: string,
  stepTexts: string[]
): {
  featureLine: number
  scenarioLine: number
  stepLines: number[]
  stepKeywords: string[]
} {
  const stepCount = stepTexts.length
  if (!featureContent) {
    return {
      featureLine: 1,
      scenarioLine: 1,
      stepLines: [],
      stepKeywords: Array<string>(stepCount).fill('')
    }
  }

  const lines = featureContent.split('\n')
  const stepRe = /^\s*(Given|When|Then|And|But)\s+/i
  let featureLine = 1
  let scenarioLine = 1
  const stepLines: number[] = []
  const stepKeywords: string[] = []

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]
    const lineNum = i + 1

    if (featureLine === 1 && /^\s*Feature:/i.test(line)) {
      featureLine = lineNum
      continue
    }

    if (/^\s*Scenario:/i.test(line) && line.includes(scenarioName)) {
      scenarioLine = lineNum
      for (
        let j = i + 1;
        j < lines.length && stepLines.length < stepCount;
        j++
      ) {
        if (/^\s*(?:Scenario:|Feature:)/i.test(lines[j])) {
          break
        }
        const m = stepRe.exec(lines[j])
        if (m) {
          stepLines.push(j + 1)
          stepKeywords.push(m[1])
        }
      }
      break
    }
  }

  while (stepKeywords.length < stepCount) {
    stepKeywords.push('')
  }
  return { featureLine, scenarioLine, stepLines, stepKeywords }
}

/** Maps Cucumber parameter type placeholder names to their regex equivalents. */
const CUCUMBER_TYPE_PATTERNS: Record<string, string> = {
  int: '-?\\d+',
  float: '-?\\d+(?:\\.\\d+)?',
  string: '(?:"[^"]*"|\'[^\']*\')',
  word: '\\S+'
}

/**
 * Convert a Cucumber expression pattern to a regular expression and test it
 * against the given step text. Handles {int}, {float}, {string}, {word}, and
 * arbitrary {type} placeholders.
 */
function matchesCucumberExpression(pattern: string, text: string): boolean {
  if (pattern === text) {
    return true
  }
  const regexSource = pattern
    .split(/(\{[^}]*\})/)
    .map((part, idx) => {
      if (idx % 2 === 1) {
        const type = part.slice(1, -1)
        return CUCUMBER_TYPE_PATTERNS[type] ?? '[\\s\\S]+'
      }
      return part.replace(/[|\\{}()[\]^$+*?.]/g, '\\$&')
    })
    .join('')
  try {
    return new RegExp(`^${regexSource}$`).test(text)
  } catch {
    return false
  }
}

/**
 * Find the file and 1-based line number of the step definition that matches
 * the given step text. Searches the provided step definition files in order.
 * Handles both string/Cucumber-expression patterns and regex literals.
 */
export function findStepDefinitionLine(
  stepDefFiles: Array<{ filePath: string; content: string }>,
  stepText: string
): StepLocation | null {
  const stepDefRe = /(?:Given|When|Then|And|But)\s*\(/i

  for (const { filePath, content } of stepDefFiles) {
    const lines = content.split('\n')
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i]
      if (!stepDefRe.test(line)) {
        continue
      }

      // String / Cucumber-expression: Given('pattern', ...) or Given("pattern", ...)
      const literalMatch = line.match(
        /(?:Given|When|Then|And|But)\s*\(\s*(['"`])(.*?)\1/i
      )
      if (literalMatch) {
        if (matchesCucumberExpression(literalMatch[2], stepText)) {
          return { filePath, line: i + 1 }
        }
        continue
      }

      // Regex literal: Given(/pattern/flags, ...)
      const regexMatch = line.match(
        /(?:Given|When|Then|And|But)\s*\(\s*\/(.+?)\/([gimy]*)/i
      )
      if (regexMatch) {
        try {
          if (new RegExp(regexMatch[1], regexMatch[2]).test(stepText)) {
            return { filePath, line: i + 1 }
          }
        } catch {
          // invalid regex — skip
        }
      }
    }
  }
  return null
}

// ---------------------------------------------------------------------------
// Port / network helpers (used by the plugin startup)
// ---------------------------------------------------------------------------

const log = logger('@wdio/nightwatch-devtools')

export function isPortInUse(port: number, hostname: string): Promise<boolean> {
  return new Promise((resolve) => {
    const server = net.createServer()
    server.once('error', () => resolve(true))
    server.once('listening', () => server.close(() => resolve(false)))
    server.listen(port, hostname)
  })
}

export async function findFreePort(
  startPort: number,
  hostname: string
): Promise<number> {
  let port = startPort
  while (await isPortInUse(port, hostname)) {
    log.warn(`Port ${port} is in use, trying ${port + 1}...`)
    port++
  }
  return port
}

export function resolveNightwatchConfig(): string | undefined {
  // Prefer the config explicitly passed via -c / --config to avoid picking up
  // an unrelated config file that happens to sit higher in the directory tree.
  const configFlagIdx = process.argv.findIndex(
    (arg) => arg === '--config' || arg === '-c'
  )
  if (configFlagIdx !== -1 && process.argv[configFlagIdx + 1]) {
    const argvConfig = process.argv[configFlagIdx + 1]
    const resolved = path.isAbsolute(argvConfig)
      ? argvConfig
      : path.resolve(process.cwd(), argvConfig)
    if (fs.existsSync(resolved)) {
      return resolved
    }
  }

  // Fallback: walk up the directory tree
  let dir = process.cwd()
  const root = path.parse(dir).root
  while (dir && dir !== root) {
    for (const file of CONFIG_FILENAMES) {
      const candidate = path.join(dir, file)
      if (fs.existsSync(candidate)) {
        return candidate
      }
    }
    const parent = path.dirname(dir)
    if (parent === dir) {
      break
    }
    dir = parent
  }
  return undefined
}
