name: Manual NPM Publish

on:
  workflow_dispatch:
    inputs:
      distTag:
        description: 'NPM tag (e.g. use "next" to release a test version)'
        required: false
        type: string
        default: 'latest'

env:
  NPM_CONFIG_PROVENANCE: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: 'main'
          fetch-depth: 0
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: .nvmrc
          registry-url: "https://registry.npmjs.org"
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          version: 10.26.1
          run_install: true
      - name: Git Setup
        run: |
          git config --global user.email "bot@webdriver.io"
          git config --global user.name "WebdriverIO Release Bot"
      - name: Install Dependencies
        run: pnpm install
      - name: Build
        run: pnpm -r build
      - name: Consume changesets and publish
        run: |
          npx changeset version
          npx changeset publish --tag "$DIST_TAG"
          git push origin main --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          DIST_TAG: ${{ inputs.distTag }}
